#theme: jekyll-theme-cayman
#theme: jekyll-theme-slate

title: BM2331 - Decoding DNA
description: Bioinformatics I Tutorial Materials

plugins:
- jekyll-remote-theme
remote_theme: niklasbuschmann/contrast
